// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOV8Ufh7_veqa4iz3MtQGzTUbgBCssr60',
    appId: '1:258248146239:web:d23b00e8a8aec99c49278a',
    messagingSenderId: '258248146239',
    projectId: 'authorization-9f41e',
    authDomain: 'authorization-9f41e.firebaseapp.com',
    storageBucket: 'authorization-9f41e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9WNBgXJKKDBpfyXbbbyqVu48HVYg_oIc',
    appId: '1:258248146239:android:d25d58af87a5fbe049278a',
    messagingSenderId: '258248146239',
    projectId: 'authorization-9f41e',
    storageBucket: 'authorization-9f41e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPhdZOFe4COYYxkiiSrY_LO4FBU_QvJ9c',
    appId: '1:258248146239:ios:57648373daae8c6a49278a',
    messagingSenderId: '258248146239',
    projectId: 'authorization-9f41e',
    storageBucket: 'authorization-9f41e.appspot.com',
    iosClientId:
        '258248146239-vhoq56aph04ug3o55bst3ukc5p7rr324.apps.googleusercontent.com',
    iosBundleId: 'com.example.alarmproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPhdZOFe4COYYxkiiSrY_LO4FBU_QvJ9c',
    appId: '1:258248146239:ios:6c5a1db5b324401b49278a',
    messagingSenderId: '258248146239',
    projectId: 'authorization-9f41e',
    storageBucket: 'authorization-9f41e.appspot.com',
    iosClientId:
        '258248146239-hlf2mtjdntq2r13c4354n6ofg246h1gb.apps.googleusercontent.com',
    iosBundleId: 'com.example.alarmproject.RunnerTests',
  );
}
